name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: hollowlatte/JavaGuide
        TARGET_BRANCH: github-pages
        BUILD_SCRIPT: pnpm && vuepress build docs
        BUILD_DIR: ./dist/
